# Generated by Django 4.2.11 on 2024-04-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('address2', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('choose_position', models.CharField(max_length=100)),
                ('year_of_experience', models.IntegerField()),
                ('resume', models.FileField(max_length=255, upload_to='uploads/')),
            ],
        ),
    ]
